# https://github.com/actions/upload-release-asset

# This is the command I used to test on a fork of the repo
# git add . && git commit -m a && npm version patch && git push && git push --tags

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.3]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Get the file name
        id: get_file_name
        run: echo ::set-output name=result::$(node -e 'const p = require("./package.json"); console.log(`${p.name}-${p.version}`)')
      - name: Git Version
        id: git_describe
        run: echo ::set-output name=result::$(git describe --abbrev=4)
      - name: NPM install
        uses: bahmutov/npm-install@v1
      - name: Build and package
        run: npm run build:package
        env:
          PACKAGER_DEST_FILE: ${{ steps.get_file_name.outputs.result }}
          CI: false # TODO Linting errors cause the build to fail when CI is true (default)
          REACT_APP_GA_TRACKING_CODE: ${{ secrets.REACT_APP_GA_TRACKING_CODE }}
          REACT_APP_RESUME_VERSION: ${{ steps.git_describe.outputs.result }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true
      - name: Upload Release Asset (zip)
        id: upload-release-asset-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./package-outputs/${{ steps.get_file_name.outputs.result }}.zip
          asset_name: ${{ steps.get_file_name.outputs.result }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset (gzip)
        id: upload-release-asset-tgz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package-outputs/${{ steps.get_file_name.outputs.result }}.tgz
          asset_name: ${{ steps.get_file_name.outputs.result }}.tgz
          asset_content_type: application/gzip
      - name: Publish release
        uses: StuYarrow/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}
      - name: Deploy with gh-pages
        run: |
          git remote add github_upstream https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>" -o "github_upstream"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
